window.localizationResources = {
    langEN: "ЕН",
    langBG: "БГ",
    homePageTitle: "Главна Страница",
    riddlePageTitle: "Загадки",
    importPageTitle: "Импортиране",
    addRoomPageTitle: "Добави Стая",
    addRiddlePageTitle: "Добави Загадка",
    documentationPageTitle: "Документация",
    filterSearch: "Търсене:",
    filterLanguage: "Език:",
    filterDifficulty: "Трудност:",
    filterTimeLimit: "Време за Решение (мин):",
    filterPlayers: "Играчи:",    
    filterSubmit: "Филтрирай",
    filterClear: "Изчистс",
    filterSearchSubmit: "Търси",
    min: "Мин:",
    max: "Макс:",
    exportRooms: "Експортирай Стаи",
    typeLabel: "Тип:",
    problemLabel: "Задача:",
    solutionLabel: "Решение:",
    imageLabel: "URL на Картинка:",
    imagePlaceholder: "URL:",
    applyButton: "Приложи",
    cancelButton: "Отмени",
    addButton: "Добави",
    deleteButton: "Изтрии",
    saveButton: "Запази",
    importButton: "Импорторай",
    exportButton: "Експортирай",
    updateButton: "Обнови",
    addRemoveRiddlesButton: "Добави/Премахни Загадки",
    currentRiddlesTitle: "Текущи Загадки:",
    addedRiddlesTitle: "Добавени Загадки:",
    riddlesToAddTitle: "Избери Загадки за Добавяне:",
    importRoomsTitle: "Импортирай Стая/Стаи",
    importRiddlesTitle: "Импортирай Загадка/Загадки",
    browsePlaceholder: "Търси...",
    minPlayersLabel: "Минимален Брой Играчи:",
    maxPlayersLabel: "Максимален Брой Играчи:"
};