window.localizationResources = {
    langEN: "EN",
    langBG: "BG",
    homePageTitle: "Home Page",
    riddlePageTitle: "Riddles",
    importPageTitle: "Import",
    addRoomPageTitle: "Add Room",
    addRiddlePageTitle: "Add Riddle",
    documentationPageTitle: "Documentation",
    filterSearch: "Name:",
    filterLanguage: "Language:",
    filterDifficulty: "Difficulty:",
    filterTimeLimit: "Time to Solve (min):",
    filterPlayers: "Players:",
    IntPlaceholder: "Integer",    
    filterSubmit: "Filter",
    filterClear: "Clear",
    filterSearchSubmit: "Search",
    min: "Min:",
    max: "Max:",
    exportRooms: "Export Rooms",
    typeLabel: "Type:",
    problemLabel: "Problem:",
    solutionLabel: "Solution:",
    imageLabel: "Image URL:",
    imagePlaceholder: "URL:",
    applyButton: "Apply",
    cancelButton: "Cancel",
    addButton: "Add",
    deleteButton: "Delete",
    saveButton: "Save",
    importButton: "Import",
    exportButton: "Export",
    updateButton: "Update",
    addRemoveRiddlesButton: "Add/Remove Riddles",
    currentRiddlesTitle: "Current Riddles:",
    addedRiddlesTitle: "Added Riddles:",
    riddlesToAddTitle: "Choose Riddles to Add:",
    importRoomsTitle: "Import Room(s)",
    importRiddlesTitle: "Import Riddle(s)",
    browsePlaceholder: "Browse...",
    minPlayersLabel: "Minimum Players:",
    maxPlayersLabel: "Maximum Players:",
    titlePlaceholder: "Name:"
};